:source-highlighter: rouge
:toc:

= Utilihive SFTP Server Stub

SFTP Server Stub is a Kotlin based project that runs an in-memory SFTP server while your tests are running.
It uses the SFTP server of the
http://mina.apache.org/sshd-project/index.html[Apache SSHD] project.
It is made to simplify the functional testing of https://docs.utilihive.io/utilihive-integration/core-concepts/flows[integration flows]
written for https://docs.utilihive.io/utilihive-integration/core-concepts/flow-server[Utilihive flow-server]
by providing a mock/stub of an SFTP server and basic functions for manipulating files on it.
However, it is not dependent on the Utilihive platform and can be used independently.

SFTP Server Stub is published under the
https://www.apache.org/licenses/LICENSE-2.0["Apache license, version 2.0"] and is originally based on Stefan Birkner's
https://github.com/stefanbirkner/fake-sftp-server-lambda[Fake SFTP Server Lambda] library, though rewritten in Kotlin.
It requires at least JDK 11.

== Installation

SFTP Server Stub is available from
https://central.sonatype.com/search?smo=true&q=utilihive-backend-stub-sftp[Maven Central].
You only need to add the following dependency to your project's `pom.xml` file:

[source,xml]
----
<dependency>
  <groupId>com.greenbird.utilihive.stubs</groupId>
  <artifactId>utilihive-backend-stub-sftp</artifactId>
  <version>LATEST_VERSION</version>
  <scope>test</scope>
</dependency>
----

== Usage

SFTP Server Stub is used by wrapping your test code with the `withSftpServer` scope function.
For example:

[source,kotlin]
----
import com.greenbird.utilihive.stubs.sftp.SftpServerTestContext.Companion.withSftpServer

class TestClass {
  @Test
  fun someTestCase() =
    withSftpServer {
      // test code
      ...
    }
}
----

`withSftpServer` starts an SFTP server before executing the test code and shuts down the server afterwards.
The test code uses the provided server object to obtain information about the running server or leverage additional features of SFTP Server Stub.

By default, the SFTP server listens on an auto-allocated port.
During the test, this port can be read from the `port` property.
If you need to specify a custom port, you can pass an argument to the scope function in the following manner:

[source,kotlin]
----
withSftpServer(port = 1234) {
  println(port) // 1234

  ...
}
----

You can interact with the SFTP server by using the SFTP protocol with password authentication.
By default, the server accepts any username and password pair, but you can restrict it to specific pairs.
For example:

[source,kotlin]
----
withSftpServer {
  addUser("username", "password")
  addUser("username2", "password2")

  ...
}
----

=== Creating Directories

If you need an empty directory on the SFTP server, you can use the
`createDirectory()` function that accepts multiple string arguments depending on the desired number of directories.
For example:

[source,kotlin]
----
withSftpServer {
  createDirectory("a/directory")
  createDirectories(
    "another/directory",
    "yet/another/directory"
  )

  // code that reads from or writes to those directories
  ...
}
----

=== Testing Code that Reads Files

If you test code that reads files from an SFTP server, then you need to make sure the server provides those files.
The `putFile()` function can either create a file with the provided string content or read from an actual local file.
For example:

[source,kotlin]
----
withSftpServer {
  // add a text file
  putFile("directory/file.txt", "content of file")

  // add a binary file from input stream
  val inputStream = getClass().getResourceAsStream("data.bin")
  putFile("directory/fileFromInputStream.bin", inputStream)

  // code that reads the file using the SFTP protocol
  ...
}
----

=== Testing Code that Writes Files

If you test code that writes files to an SFTP server, and you need to verify the upload of those files, use the `getFileText()` and `getFileBytes()` functions.
For example:

[source,kotlin]
----
withSftpServer {
  // code that uploads files using the SFTP protocol
  ...

  // read file data
  val textFileContent = getFileText("directory/file.txt")
  val binaryFileContent = getFileBytes("directory/file.bin")

  // verify contents
  ...
}
----

=== Testing Existence of Files and Directories

If you want to verify the existence of a file or directory, or even the files that might exist within that directory, you can use the `getPath()` function.
For example:

[source,kotlin]
----
withSftpServer {
  // code that uploads or deletes the files
  ...

  val path = getPath("directory/file.txt")

  // test on the path
  path.exists
  path.isDirectory
  path.listDirectoryEntries("*.txt")
}
----

=== Deleting all Files

If you want to reuse the SFTP server within the same test, you can delete all files and directories with the `deleteAllFilesAndDirectories()` function.
For example:

[source,kotlin]
----
withSftpServer {
  // code that created several files
  ...

  deleteAllFilesAndDirectories()

  // clean slate for the rest of the test
  ...
}
----

Note that this is rarely necessary, because the `withSftpServer` scope function ensures that the test starts and ends with a clean SFTP.

=== Absolute vs Relative Paths

The SFTP Server Stub supports both absolute paths (e.g., `/path/to/file`) and relative paths (e.g., `path/to/file`).
Quite commonly, SFTP servers present clients with a limited view of the filesystem, where the root of what's available to the user is presented as `/`, and that is the initial directory where the user starts after login.
In such a case, absolute and relative paths will behave effectively the same and point to the same place in the filesystem.

If that's not your case, and the server puts you in a directory like `/home/myuser` after logging in, then you should set the path when initializing the context.
For example:

----
withSftpServer(initialDirectory = "/home/myuser") {
  ...
}
----

Paths without a `/` prefix are interpreted relative to the given `initialDirectory`.
In the example above, the path `/files/in` still points to `/files/in`, but the path `files/in` points to `/home/myuser/files/in`.

== Usage in Flow Testing

NOTE: This information only applies if you are specifically developing on the Utilihive platform.

Let's assume you have a flow that contains a
https://docs.utilihive.io/utilihive-integration/writing-testing-flows/processors/read-files/[readFiles]
source processor that reads CSV files from an SFTP server and processes them (typically with a follow-up https://docs.utilihive.io/utilihive-integration/writing-testing-flows/processors/parse-csv/[parseCsv] processor).
In this situation, you would want a functional test that uploads the CSV file to the SFTP server (which then triggers file ingestion by the in-memory flow-server) and asserts that the file has been moved from the source folder (defined by the `path` property) to the successfully read folder (defined by the `moveToFolder` property).

The following example shows how you could accomplish this as a JUnit test:

[source,kotlin]
----
@Test
fun `WHEN putting file on sftp THEN file is read and moved to a correct directory`(
    ctx: ConcurrentTestContext
) = withSftpServer {
    ctx.addFlowTestConfig {
        authConfig(...)
        flow(mySftpSourceFlow)
    }

    flowTest(ctx) {
        val sourceFileContent = "column1;column2\nval1;val2\nval3;val4"
        val sourceFilePath = "source-path"
        val moveToFilePath = "move-to-path"

        // set up directories and file content
        createDirectories(sourceFilePath, moveToFilePath)
        putFile("$sourceFilePath/test.csv", sourceFileContent, UTF_8)

        // verify that file was consumed from source location
        await().atMost(DEFAULT_TIMEOUT).until { !getPath("$sourceFilePath/test.csv").exists() }

        // verify that file was moved
        await().atMost(DEFAULT_TIMEOUT).until {
            getPath(moveToFilePath).exists() &&
                getFileText("$moveToFilePath/test.csv", UTF_8).contentEquals(sourceFileContent)
        }

        // other testing you need to do on the ingested csv data
        ...
    }
}
----

The above example uses the `org.awaitility:awaitility` library to help with asynchronous testing.
Please note that your flow's `readFiles` processor must set the `pollingFrequencySeconds` property lower than the `DEFAULT_TIMEOUT` used for the `await()` duration.
Otherwise, the first file won't be read before the test times out.

== Contributing

If you have a feature request, found a bug, or simply have a question about SFTP Server Stub, you can do the following:

* https://github.com/utilihive/utilihive-backend-stub-sftp-server/issues[Create an issue]
describing the bug and/or use case.
* Create a pull request for a bug fix.
In such a case, the scenario must be covered by a unit test.
See the https://docs.github.com/en/get-started/quickstart/github-flow[GitHub Flow guide] for more advice on collaborating on projects.

== Building and Releasing

To release your code, create a pull request from your branch to `main`.
After someone approves it and merges to `main`, the GitHub workflow takes care of the versioning, tagging, signing, and publishing to the Maven Central repository.
It also creates a new GitHub release (using the `CHANGELOG.md` file as the description).
