name: Release and publish to Maven Central

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Release prepare
        uses: qcastel/github-actions-maven-release@master
        env:
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        with:
          release-branch-name: "main"

          git-release-bot-name: "release-bot"
          git-release-bot-email: "release-bot@greenbird.com"

          maven-args: "-P release -Dmaven.javadoc.skip=true -DskipTests -Ddockerfile.skip -DdockerCompose.skip"

          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          gpg-enabled: "true"
          gpg-key-id: ${{ secrets.GPG_KEY_ID }}
          gpg-key: ${{ secrets.GPG_PRIVATE_KEY_BASE64 }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
