name: Release and publish to Maven Central

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Increment Version
        run: |
          ./mvnw build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.incrementalVersion} versions:commit
          export version=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          git config user.name release-bot
          git config user.email release-bot@greenbird.com
          git add .
          git commit -m "Release $version"
          git push
          git tag -a $version -m "$version"
          git push origin $version

      - name: Release to Nexus Repository
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus_username: ${{ secrets.OSSRH_USERNAME }}
          nexus_password: ${{ secrets.OSSRH_PASSWORD }}

      - name: Increment to next development version
        run: |
          ./mvnw build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT versions:commit
          export version=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          git config user.name release-bot
          git config user.email release-bot@greenbird.com
          git add .
          git commit -m "prepare for next development iteration"
          git push
