name: Release and publish to Maven Central

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v3
      - name: Build and Test
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "clean install"
      - name: Release and deploy to Maven Central
        uses: mg-smartrent/github-actions-maven-release@master
        with:
          release-branch-name: "main"
          git-release-bot-name: "release-bot"
          git-release-bot-email: "release-bot@greenbird.com"
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          gpg-enabled: "true"
          gpg-key-id: ${{ secrets.GPG_KEY_ID }}
          gpg-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

          # Release
          maven-repo-server-id: ossrh
          maven-repo-server-username: ${{ secrets.OSSRH_USERNAME }}
          maven-repo-server-password: ${{ secrets.OSSRH_PASSWORD }}
          maven-release-args: "-P release -Dskip.unit.tests=true -Dskip.integration.tests=true"

          # Publish artifacts to Maven central
          maven-publish-args: "-P release -Dskip.unit.tests=true -Dskip.integration.tests=true"
          maven-release-publish: "true"
          maven-snapshot-publish: "false"
