name: Release and publish to Maven Central

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_TOKEN }}

      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Increment Version
        id: increment_version
        run: |
          mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.incrementalVersion} versions:commit
          export version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          git config user.name Greenbird CI
          git config user.email greenbird-ci@greenbird.com
          git add .
          git commit -m "[ci skip] Release $version"
          git push
          git tag -a $version -m "$version"
          git push origin $version
          echo "versionTag=$version" >> $GITHUB_ENV
          mvn -P release clean package

      - name: Create Github release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/*.jar"
          tag: ${{ env.versionTag }}
          bodyFile: CHANGELOG.md

      - name: Release to Nexus Repository
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus_username: ${{ secrets.OSSRH_USERNAME }}
          nexus_password: ${{ secrets.OSSRH_PASSWORD }}
          maven_profiles: release

      - name: Increment to next development version
        run: |
          mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT versions:commit
          export version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          git config user.name Greenbird CI
          git config user.email greenbird-ci@greenbird.com
          git add .
          git commit -m "[ci skip] prepare for next development iteration"
          git push
